uploads = []

[[generated]]
id = "SqT7mGp4yQfwBQTpm8imS"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "ai brain agent icon"

[[outputs]]
id = "GTov11y9B8xinj-VI7pxu"
uri = "file://stubs.md"
type = "text"
title = "ARIA Stub Registry"
